import { Version } from 'eth-sig-util';

import { ITxid } from '@pollum-io/sysweb3-utils';

import type LedgerHwAppEth from '@ledgerhq/hw-app-eth';

export type GetPublicKeyParams = { hdPath: string };
export type GetPublicKeyResponse = Awaited<
  ReturnType<LedgerHwAppEth['getAddress']>
> & {
  chainCode: string;
};

export type LedgerSignTransactionParams = { hdPath: string; tx: string };
export type LedgerSignTransactionResponse = Awaited<
  ReturnType<LedgerHwAppEth['signTransaction']>
>;

export type LedgerSignMessageParams = { hdPath: string; message: string };
export type LedgerSignMessageResponse = Awaited<
  ReturnType<LedgerHwAppEth['signPersonalMessage']>
>;

export type LedgerSignTypedDataParams = {
  hdPath: string;
  domainSeparatorHex: string;
  hashStructMessageHex: string;
};
export type LedgerSignTypedDataResponse = Awaited<
  ReturnType<LedgerHwAppEth['signEIP712HashedMessage']>
>;

// eslint-disable-next-line @typescript-eslint/consistent-type-definitions
export interface LedgerBridge {
  isDeviceConnected: boolean;

  init(bridgeUrl: string): Promise<void>;

  destroy(): Promise<void>;

  attemptMakeApp(): Promise<boolean>;

  updateTransportMethod(transportType: string): Promise<boolean>;

  getPublicKey(params: GetPublicKeyParams): Promise<GetPublicKeyResponse>;

  deviceSignTransaction(
    params: LedgerSignTransactionParams
  ): Promise<LedgerSignTransactionResponse>;

  deviceSignMessage(
    params: LedgerSignMessageParams
  ): Promise<LedgerSignMessageResponse>;

  deviceSignTypedData(
    params: LedgerSignTypedDataParams
  ): Promise<LedgerSignTypedDataResponse>;
}

export interface BlockbookUTXO {
  txid: string;
  vout: number;
  value: string;
  height: number;
  confirmations: number;
  address: string;
  path: string;
}

// Generated by https://quicktype.io

export interface BlockbookTransaction {
  txid: string;
  version: number;
  vin: Vin[];
  vout: Vout[];
  blockHash: string;
  blockHeight: number;
  confirmations: number;
  blockTime: number;
  value: string;
  valueIn: string;
  fees: string;
  hex: string;
}

export interface Vin {
  txid: string;
  sequence: number;
  n: number;
  addresses: string[];
  isAddress: boolean;
  value: string;
}
export type UTXOPayload = {
  utxos: BlockbookUTXO[];
};
export interface Vout {
  value: string;
  n: number;
  hex: string;
  addresses: string[];
  isAddress: boolean;
}

export interface IUTXOMethods {
  getUtxos: ({
    accountIndex,
  }: {
    accountIndex: number;
  }) => Promise<BlockbookUTXO[]>;
  sendTransaction: ({
    accountIndex,
    amount,
    receivingAddress,
  }: {
    accountIndex: number;
    amount: number;
    receivingAddress: string;
  }) => Promise<ITxid>;
  getUtxoAddress: ({
    coin,
    index,
    slip44,
  }: {
    coin: string;
    index: number;
    slip44?: string | undefined;
  }) => Promise<string>;
  getXpub: ({
    index,
    coin,
    slip44,
    withDecriptor,
  }: {
    index: number;
    coin: string;
    slip44?: string | undefined;
    withDecriptor?: boolean | undefined;
  }) => Promise<string>;
  verifyUtxoAddress: (accountIndex: number) => Promise<string>;
}

interface MessageTypeProperty {
  name: string;
  type: string;
}
export interface MessageTypes {
  EIP712Domain: MessageTypeProperty[];
  [additionalProperties: string]: MessageTypeProperty[];
}

export interface IEvmMethods {
  getEvmAddressAndPubKey: ({
    accountIndex,
  }: {
    accountIndex: number;
  }) => Promise<{
    address: string;
    publicKey: string;
  }>;
  signEVMTransaction: ({
    rawTx,
    accountIndex,
  }: {
    rawTx: string;
    accountIndex: number;
  }) => Promise<{
    s: string;
    v: string;
    r: string;
  }>;
  signPersonalMessage: ({
    message,
    accountIndex,
  }: {
    message: string;
    accountIndex: number;
  }) => Promise<string>;
  signTypedData: ({
    version,
    data,
    accountIndex,
  }: {
    version: Version;
    data: any;
    accountIndex: number;
  }) => Promise<string>;
}
